---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: medimesh-mongo-secret
  namespace: medimesh-db
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgA+cSHHbVNpDNTS7qSs+POlf0Zp/jcve4t/c08+C2+puDGcqDRIUWF+MpOCS4Q961NwwYaxp5byRR2jG1ecPQ0+8v02P/4tpxNo6s2Pb6aXRlOBsD9hiqY5Xvx8egKv13vFJf35/jhvLwHVZx/dS4F5TB9iuQG3tFPkN9zQtlTXyXw3JB/d0pGyMZ69neLEMw5rPjmq8n+atliQ9veXQ00kW1TcATrVT99pTi9J5JUILGz2FBDM9hcfmEeuazo2k46886Meu7NqGd6qk2jLvNcsgVwfcLqUHMQlqNTd1V42jVNC3436e5h0ZExof+Q1Fk32Uc0w/WAy8fGIt6RaOflziRY5rEVjDHcPjTwi8Z9xTChs4Fc8B17e55yDmkLBsQh6iyxHdz3ciqx0KB1StJjZfFqh3Kk2qP60JbhxNv5BZNHbEjeWPDwxGSSuJ593QOBObhaYMwl3scT3mlJu/1sgZIErMGSos2S/uNfV7IjE6r0H0twemLLllJMLXgqLwU/amfWZ0yNNZ5eQ8L9NpQeLYKJrfHO6BjUHxk65MXDLE+mnoCmlWJC3/B8OTELLwO/Tdb0GZdwBB+vc7dSPB4c49PH0ERvfuj0rVeJ9E5L3l+5IapuU6gtLWbcqXUHYxmYs0nwCllPTXbifQTPd6Zc9pdw2wgal4f7erHrOxikDy6HuD85rVXhYNpOPVTgodfQ4gHgGSfJDlx/gmz3ZgmhJ
    MONGO_INITDB_ROOT_USERNAME: AgCDgentQGP1+GQML+eIqFTbnAJGxBGUkjVxMntHy/fhj1Dn1M4v8T1UdP8ntAsbOq2DC1MHXqvgQ/F7WN3uHZJLvHPZj4aXO7r565oXId5m3fLYIK3/PquDlppGddbWFBQtxICG3P4m1JwzJ4HAb4VGialFmPCUsmZ67ALsNN3ToP8i7forL/BFiDBBz5P13O0LT1ToFWVUYEC7kzU7r7Jnn6hm7tKbs+vDjlqYgbI5aaD0UhxQFtK6t2V4aTcys8QQlQMWLM9zlm8+XW9PQahxOsADuut0115RSSCAp9K9gQw914HJJiIPcEd2CCCxamGdvIeRViJR1V8v6zLElpoYWGlsavmRaHjiTnBkUacxO1U/R31GnINtO0yrEsq+Vd0y0+wTR7zaqUUm24BwAjd5MR60mr1RuQ6OPbiNzSRDDMEwlaZo+abFqNpFr2QDEYk4+85q6xUAl7friNstvZ8CzfqhkIzsquW+Qqlhq0zTEZKaM5P3nfw9XBKltAut3N/8EV+2V/M1mbqFY91UyerZvmYTIyEH22tvUD9rIjegP146gX7xEho1YH8SvqykgOqoNB0jvaLfpR0Q2WQLR8861oXkdEK/MpgbstefzI3O0YsiOtdrvqvHdIsKiJ6YbHVPzM5gp9mM92nbaG1ZlqX8W7oV/ivwHaWD3Cx2ebb9maqx6w55kNnfbl+Iiu0AQmGoOtRTkh5vFXxle1jh
  template:
    metadata:
      creationTimestamp: null
      name: medimesh-mongo-secret
      namespace: medimesh-db
    type: Opaque
