# Frontend Active (Blue) Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespaces.frontend }}
  labels:
    app: {{ .Values.name }}
    tier: frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.name }}
    tier: frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
---
# Frontend Preview (Green) Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-preview
  namespace: {{ .Values.namespaces.frontend }}
  labels:
    app: {{ .Values.name }}
    tier: frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.name }}
    tier: frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
