# ─── MediMesh Forum Service Values ────────────────────────
name: medimesh-forum
replicas: 2
image:
  repository: bharath44623/medimesh_medimesh-forum
  tag: "v1.0.4"
imagePullPolicy: Always
containerPort: 5009
dbName: medimesh-forum-db
service:
  name: medimesh-forum-svc
  port: 5009
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
extraEnv: []
# Previously global values — now local
namespaces:
  backend: medimesh-backend
  db: medimesh-db
mongo:
  host: medimesh-mongodb
  port: 27017
  replicaSet: rs0
