# Auth Service - Active (Blue)
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespaces.backend }}
  labels:
    app: {{ .Values.name }}
    tier: backend
spec:
  selector:
    app: {{ .Values.name }}
    tier: backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
---
# Auth Service - Preview (Green)
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-preview
  namespace: {{ .Values.namespaces.backend }}
  labels:
    app: {{ .Values.name }}
    tier: backend
spec:
  selector:
    app: {{ .Values.name }}
    tier: backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
